services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=root
      - ODOO_SUPERADMIN=admin   # clave del superadmin
    volumes:
      - "C:/POS/odoo-addons:/mnt/extra-addons"
      - "C:/POS/odoo-data:/var/lib/odoo"

volumes:
  db-data:
  odoo-data:
